######################################################################
# Automatically generated by qmake (3.0) Thu Feb 22 16:28:40 2018
######################################################################

TEMPLATE = app
TARGET = TINY_WebServer
INCLUDEPATH += .

# Input
SOURCES += tiny.c \
    csapp.c

HEADERS += \
    csapp.h
